version: '3'
services:
  mongo:
    restart: always
    container_name: mongodocker
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
     - '27017:27017'
